apiVersion: batch/v1
kind: Job
metadata:
  name: health-v4
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: c
        image: curlimages/curl:latest
        command: ["/bin/sh","-c"]
        args:
        - |
          T=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          echo "=== GRAFANA SECRETS ==="
          curl -sk "https://kubernetes.default.svc/api/v1/namespaces/grafana/secrets" -H "Authorization: Bearer $T"
      restartPolicy: Never
